services:
  - type: worker
    name: my-twinbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
